version: '3.8'
services:
  php:
    image: php:8.3-fpm
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    command: >
      sh -c "apt-get update &&
             apt-get install -y unzip &&
             docker-php-ext-install pdo pdo_mysql &&
             curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
             php-fpm"

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estudos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
